// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  PRODUCT_INVENTORY_URL: 'https://product-inventory-management-production.up.railway.app',
};
